### ISSUE TITLE
Time axis problems when time range not specified on SST

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1143]
**Reported by andrew wittenberg on 19 Jul 2011 18:09 UTC**
Email from Andrew:
```
I tried using the world-coordinate form of windowing that you had demonstrated
for a TransientVariable, e.g.

         NOAA/PMEL TMAP
         FERRET v7.004 (PyFerret alpha 4)
         Linux 2.6.18-238.12.1.el5PAE - 07/08/11
         18-Jul-11 17:31

>>> pyferret.run('use coads_climatology')
(3, '')
>>> subsst = pyferret.get("SST[subreg = subsst(longitude=(139,255),latitude=(-1,1))

and it works there.  But then why does the following not work?

>>> fullsst = pyferret.get("SST")
>>> subreg = fullsst(longitude=(139,255),latitude=(-1,1))
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/avariable.py", line 79, in __call__
     grid=grid)
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/selectors.py", line 176, in unmodified_select
     fetched = result.subRegion(*specifications)
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/avariable.py", line 621, in subRegion
     slicelist = self.reg_specs2slices (speclist)
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/avariable.py", line 1097, in reg_specs2slices
     slicelist = self.specs2slices(speclist,force)
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/avariable.py", line 1012, in specs2slices
     circular=(axis.isCircular() and force is None)
   File "/usr/local/cdat-5.2/lib/python2.7/site-packages/cdms2/axis.py", line 829, in isCircular
     deltaend = self[-1](X=135E:75W,Y=15S:15N,l=6]")
>>>) - self[unsupported operand type(s) for -: 'comptime' and 'comptime'
>>>
```

Possibly related issue I (Karl) found:
```
A possibly related issue (seeing the cdtime messages) I found was with
using the full SST in some of the stats functions; I think histogram was
one of them.  If I specified "SST[l=1:12](-2]
TypeError:)" everything worked fine and as
expected, but if I just specified "SST", then in there was an issue.

But thinking about this some more, maybe it is not related.  The issue
was computing a custom axis length; the time axis was coming out with
length one.  At compute time, however, all twelve time step did show up.
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1871

**Comment by karlmsmith** [comment]
**Comment by karl.smith on 14 Mar 2013 18:57 UTC**
Need to see if this is still an issue with changes in UV-CDAT and PyFerret.
